### ISSUE TITLE
未登录前的那个信息发送框建议取消

### ISSUE THREAD

**Issue by spysir** [okhanyu/minichat#12]
既然未登录前无法发送信息，那干脆直接取消掉那个信息发送框好了，那样页面更简洁
![99999999](https://github.com/okhanyu/minichat/assets/59646715/b5b15a68-f79a-41be-a847-bd0c3d38b1b7)

**Comment by seeyousuperman** [comment]
确实，在这个页面下，消息发送框是多余的，应该去掉，感谢🙏建议，我来处理
