### ISSUE TITLE
是否可以新增不依赖docker的部署方式

### ISSUE THREAD

**Issue by webersongao** [okhanyu/minichat#2]
1、新人不懂docker，服务器环境也存在其他项目，不希望使用docker，是否可以提供其他的部署方式教程。叩谢~
2、我使用的时候，似乎自己发送的文字也展示在左侧，这似乎跟常用的微信展示方式不一致，是否可以改为，自己发的左侧，他人发的在右侧
3、非常有创意，也非常简洁的设计，轻量级，牛逼，期待可以部署尝试一下~

**Comment by seeyousuperman** [comment]
1. https://github.com/okhanyu/minichat/releases 有二进制执行文件，可以直接下载解压运行即可，无需Docker，你可以看readme中的第三种部署方式
2. 目前UI上确实自己发的消息是在左侧的，后续会优化成右侧显示，不过目前使用气泡颜色区分的
3. 感谢🙏
