### ISSUE TITLE
[ Bug ] 后续进入房间的人发消息会出现第二条空信息

### ISSUE THREAD

**Issue by W4ddl3** [okhanyu/minichat#3]
https://github.com/okhanyu/minichat/assets/141616559/3e1388ff-f463-40d4-a2c7-8eb28ee6c68e

用的是 LibreWolf 浏览器（ Firefox内核 ），重启浏览器后就没这个 空消息 了。
暂时无法复现

**Comment by W4ddl3** [comment]
已复现

![Shot 2024-06-21 at 14 40 21@2x](https://github.com/okhanyu/minichat/assets/141616559/5cf84aae-c905-4ddd-8105-59b5c38294a8)

第一次尝试进入时，密码错误（无论是否设置密码，不设置密码，就输入密码，也会判定错误）
后面成功进去后，就会这样了


所以如果房间没密码，建议拿链接进入的人，直接不显示输 密码 框框

**Comment by seeyousuperman** [comment]
感谢捉虫，确实存在这个问题，我来修复一下。

**Comment by seeyousuperman** [comment]
已于凌晨修复此问题啦！
感谢感谢！
