### ISSUE TITLE
[ Request ] 检测房间内是否有同名用户，有的话就不准创建这个名字

### ISSUE THREAD

**Issue by W4ddl3** [okhanyu/minichat#4]
![Shot 2024-06-21 at 14 42 48@2x](https://github.com/okhanyu/minichat/assets/141616559/0a117c02-0921-463b-a267-f25518c0c26a)

实测发现，如果设置为同名，系统会自动在后面添加随机字符

个人感觉这不好，建议加个检测功能，有就提示重复

另外，对于有密码的房间
或许应该在密码正确后，再检测名字是否重复

**Comment by seeyousuperman** [comment]
您的提议很棒，目前第一版，确实有些体验不好，对于您的提议表示支持，会迭代改进

**Comment by seeyousuperman** [comment]
版本已更新，检测密码的机制已变更，同时用户名重复不再随机指定，而是提示用户名重复
