### ISSUE TITLE
[ Request ] 国际化

### ISSUE THREAD

**Issue by W4ddl3** [okhanyu/minichat#6]
![Shot 2024-06-21 at 15 39 59@2x](https://github.com/okhanyu/minichat/assets/141616559/cea874a6-7afa-4df3-bec2-b2bbe11457ce)
发现现在界面是中英文混搭，不太好
建议应该在项目初期就开始做国际化

**Comment by seeyousuperman** [comment]
目前已全部改为英文，功能上目前还有些欠缺，后面会做国际化，感谢用心的建议🙏
