### ISSUE TITLE
可否选择将一些房间的数据存到本地？

### ISSUE THREAD

**Issue by dianso** [okhanyu/minichat#7]
之前用的https://github.com/usememos/memos
最近的更新太臃肿了 
我发现你这个项目自己建立个聊天室用来发memos挺不错

**Comment by seeyousuperman** [comment]
千万别用Minichat来发memos，因为这是基于纯内存的，一旦服务器重启，数据就全部都会丢失，切记。
另外，memos目前确实有太多太多诟病的地方了，已经让太多人失望了，没关系未来我或者其他人会开发一款类似的产品，一款具有产品和用户思维的memos.

**Comment by seeyousuperman** [comment]
数据存储到本地，可以列为未来的开发计划，但我总觉得，这样的产品因该以另一种更有趣的形态存在，我再想想。

**Comment by dianso** [comment]
感谢
